/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Jun  4 14:16:18 2025


#include "RpLidar3_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(RpLidar3ParamsCOMPONENT, "yarp.device.RpLidar3")
}


RpLidar3_ParamsParser::RpLidar3_ParamsParser()
{
}


std::vector<std::string> RpLidar3_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("GENERAL::serial_port");
    params.push_back("GENERAL::serial_baudrate");
    params.push_back("GENERAL::sample_buffer_life");
    params.push_back("GENERAL::thread_period");
    params.push_back("RPLIDAR::motor_pwm");
    params.push_back("RPLIDAR::express_mode");
    params.push_back("RPLIDAR::force_scan");
    params.push_back("RPLIDAR::scan_mode");
    return params;
}


bool RpLidar3_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="GENERAL::serial_port")
    {
        paramValue = m_GENERAL_serial_port;
        return true;
    }
    if (paramName =="GENERAL::serial_baudrate")
    {
        paramValue = std::to_string(m_GENERAL_serial_baudrate);
        return true;
    }
    if (paramName =="GENERAL::sample_buffer_life")
    {
        paramValue = std::to_string(m_GENERAL_sample_buffer_life);
        return true;
    }
    if (paramName =="GENERAL::thread_period")
    {
        paramValue = std::to_string(m_GENERAL_thread_period);
        return true;
    }
    if (paramName =="RPLIDAR::motor_pwm")
    {
        paramValue = std::to_string(m_RPLIDAR_motor_pwm);
        return true;
    }
    if (paramName =="RPLIDAR::express_mode")
    {
        if (m_RPLIDAR_express_mode==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="RPLIDAR::force_scan")
    {
        if (m_RPLIDAR_force_scan==true) paramValue = "true";
        else paramValue = "false";
        return true;
    }
    if (paramName =="RPLIDAR::scan_mode")
    {
        paramValue = m_RPLIDAR_scan_mode;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string RpLidar3_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      RpLidar3_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(RpLidar3ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter GENERAL::serial_port
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("GENERAL");
        if (sectionp.check("serial_port"))
        {
            m_GENERAL_serial_port = sectionp.find("serial_port").asString();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'GENERAL::serial_port' using value:" << m_GENERAL_serial_port;
        }
        else
        {
            yCError(RpLidar3ParamsCOMPONENT) << "Mandatory parameter 'GENERAL::serial_port' not found!";
            yCError(RpLidar3ParamsCOMPONENT) << "Description of the parameter: Name of the serial port";
            return false;
        }
        prop_check.unput("GENERAL::serial_port");
    }

    //Parser of parameter GENERAL::serial_baudrate
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("GENERAL");
        if (sectionp.check("serial_baudrate"))
        {
            m_GENERAL_serial_baudrate = sectionp.find("serial_baudrate").asInt64();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'GENERAL::serial_baudrate' using value:" << m_GENERAL_serial_baudrate;
        }
        else
        {
            yCError(RpLidar3ParamsCOMPONENT) << "Mandatory parameter 'GENERAL::serial_baudrate' not found!";
            yCError(RpLidar3ParamsCOMPONENT) << "Description of the parameter: Baud rate of the serial port";
            return false;
        }
        prop_check.unput("GENERAL::serial_baudrate");
    }

    //Parser of parameter GENERAL::sample_buffer_life
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("GENERAL");
        if (sectionp.check("sample_buffer_life"))
        {
            m_GENERAL_sample_buffer_life = sectionp.find("sample_buffer_life").asInt64();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'GENERAL::sample_buffer_life' using value:" << m_GENERAL_sample_buffer_life;
        }
        else
        {
            yCError(RpLidar3ParamsCOMPONENT) << "Mandatory parameter 'GENERAL::sample_buffer_life' not found!";
            yCError(RpLidar3ParamsCOMPONENT) << "Description of the parameter: Keeps data in memory for some iterations, in order to complete the scan with the missing values (the scan is not always complete)";
            return false;
        }
        prop_check.unput("GENERAL::sample_buffer_life");
    }

    //Parser of parameter GENERAL::thread_period
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("GENERAL");
        if (sectionp.check("thread_period"))
        {
            m_GENERAL_thread_period = sectionp.find("thread_period").asInt64();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'GENERAL::thread_period' using value:" << m_GENERAL_thread_period;
        }
        else
        {
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'GENERAL::thread_period' using DEFAULT value:" << m_GENERAL_thread_period;
        }
        prop_check.unput("GENERAL::thread_period");
    }

    //Parser of parameter RPLIDAR::motor_pwm
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("RPLIDAR");
        if (sectionp.check("motor_pwm"))
        {
            m_RPLIDAR_motor_pwm = sectionp.find("motor_pwm").asInt64();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::motor_pwm' using value:" << m_RPLIDAR_motor_pwm;
        }
        else
        {
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::motor_pwm' using DEFAULT value:" << m_RPLIDAR_motor_pwm;
        }
        prop_check.unput("RPLIDAR::motor_pwm");
    }

    //Parser of parameter RPLIDAR::express_mode
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("RPLIDAR");
        if (sectionp.check("express_mode"))
        {
            m_RPLIDAR_express_mode = sectionp.find("express_mode").asBool();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::express_mode' using value:" << m_RPLIDAR_express_mode;
        }
        else
        {
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::express_mode' using DEFAULT value:" << m_RPLIDAR_express_mode;
        }
        prop_check.unput("RPLIDAR::express_mode");
    }

    //Parser of parameter RPLIDAR::force_scan
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("RPLIDAR");
        if (sectionp.check("force_scan"))
        {
            m_RPLIDAR_force_scan = sectionp.find("force_scan").asBool();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::force_scan' using value:" << m_RPLIDAR_force_scan;
        }
        else
        {
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::force_scan' using DEFAULT value:" << m_RPLIDAR_force_scan;
        }
        prop_check.unput("RPLIDAR::force_scan");
    }

    //Parser of parameter RPLIDAR::scan_mode
    {
        yarp::os::Bottle sectionp;
        sectionp = config.findGroup("RPLIDAR");
        if (sectionp.check("scan_mode"))
        {
            m_RPLIDAR_scan_mode = sectionp.find("scan_mode").asString();
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::scan_mode' using value:" << m_RPLIDAR_scan_mode;
        }
        else
        {
            yCInfo(RpLidar3ParamsCOMPONENT) << "Parameter 'RPLIDAR::scan_mode' using DEFAULT value:" << m_RPLIDAR_scan_mode;
        }
        prop_check.unput("RPLIDAR::scan_mode");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(RpLidar3ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(RpLidar3ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      RpLidar3_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: RpLidar3\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'GENERAL::serial_port': Name of the serial port\n");
    doc = doc + std::string("'GENERAL::serial_baudrate': Baud rate of the serial port\n");
    doc = doc + std::string("'GENERAL::sample_buffer_life': Keeps data in memory for some iterations, in order to complete the scan with the missing values (the scan is not always complete)\n");
    doc = doc + std::string("'GENERAL::thread_period': Acquisition thread period. The default value = 0 means maximum speed (measured duration ~75ms). It is useful to change it only if you need to slow down the device (e.g. 100ms)\n");
    doc = doc + std::string("'RPLIDAR::motor_pwm': Used by internal RPLidar APIs\n");
    doc = doc + std::string("'RPLIDAR::express_mode': Check sensor datasheet\n");
    doc = doc + std::string("'RPLIDAR::force_scan': Check sensor datasheet\n");
    doc = doc + std::string("'RPLIDAR::scan_mode': Check sensor datasheet\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device rpLidar3 --GENERAL::serial_port <mandatory_value> --GENERAL::serial_baudrate <mandatory_value> --GENERAL::sample_buffer_life <mandatory_value> --GENERAL::thread_period 0 --RPLIDAR::motor_pwm 0 --RPLIDAR::express_mode false --RPLIDAR::force_scan false --RPLIDAR::scan_mode Boost\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device rpLidar3 --GENERAL::serial_port <mandatory_value> --GENERAL::serial_baudrate <mandatory_value> --GENERAL::sample_buffer_life <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
