/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Jun  4 14:16:18 2025


#ifndef RPLIDAR2_PARAMSPARSER_H
#define RPLIDAR2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class RpLidar2.
*
* These are the used parameters:
* | Group name | Parameter name     | Type   | Units | Default Value | Required | Description                                                                                                                                                                     | Notes |
* |:----------:|:------------------:|:------:|:-----:|:-------------:|:--------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:-----:|
* | GENERAL    | serial_port        | string | -     | -             | 1        | Name of the serial port                                                                                                                                                         | -     |
* | GENERAL    | serial_baudrate    | int    | -     | -             | 1        | Baud rate of the srial port                                                                                                                                                     | -     |
* | GENERAL    | sample_buffer_life | int    | -     | -             | 1        | Keeps data in memory for some iterations, in order to complete the scan with the missing values (the scan is not always complete)                                               | -     |
* | GENERAL    | motor_pwm          | int    | -     | 0             | 0        | Used by internal RPLidar APIs                                                                                                                                                   | -     |
* | GENERAL    | thread_period      | int    | ms    | 0             | 0        | Acquisition thread period. The default value = 0 means maximum speed (measured duration ~75ms). It is useful to change it only if you need to slow down the device (e.g. 100ms) | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device rpLidar2 --GENERAL::serial_port <mandatory_value> --GENERAL::serial_baudrate <mandatory_value> --GENERAL::sample_buffer_life <mandatory_value> --GENERAL::motor_pwm 0 --GENERAL::thread_period 0
* \endcode
*
* \code{.unparsed}
* yarpdev --device rpLidar2 --GENERAL::serial_port <mandatory_value> --GENERAL::serial_baudrate <mandatory_value> --GENERAL::sample_buffer_life <mandatory_value>
* \endcode
*
*/

class RpLidar2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    RpLidar2_ParamsParser();
    ~RpLidar2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"RpLidar2"};
    const std::string m_device_name = {"rpLidar2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_GENERAL_serial_port_defaultValue = {""};
    const std::string m_GENERAL_serial_baudrate_defaultValue = {""};
    const std::string m_GENERAL_sample_buffer_life_defaultValue = {""};
    const std::string m_GENERAL_motor_pwm_defaultValue = {"0"};
    const std::string m_GENERAL_thread_period_defaultValue = {"0"};

    std::string m_GENERAL_serial_port = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    int m_GENERAL_serial_baudrate = {0}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    int m_GENERAL_sample_buffer_life = {0}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.
    int m_GENERAL_motor_pwm = {0};
    int m_GENERAL_thread_period = {0};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
